# vim:ft=kitty

## name:     OneDark Darker
## author:   Based on navarasu/onedark.nvim darker palette
## blurb:    Kitty theme matching the onedark.nvim darker variant.

# The basic colors
foreground              #A0A8B7
background              #1F2329
selection_foreground    #1F2329
selection_background    #A0A8B7

# Cursor colors
cursor                  #A0A8B7
cursor_text_color       #1F2329

# URL underline color when hovering with mouse
url_color               #4FA6ED

# Tab bar colors
active_tab_foreground   #1F2329
active_tab_background   #A0A8B7
inactive_tab_foreground #A0A8B7
inactive_tab_background #282C34

# The 16 terminal colors

# black
color0 #282C34
color8 #535560

# red
color1 #E55561
color9 #E06C75

# green
color2  #8EBD6B
color10 #A5E075

# yellow
color3  #E2B86B
color11 #E5C07B

# blue
color4  #4FA6ED
color12 #4DC4FF

# purple
color5  #BF68D9
color13 #DE73FF

# cyan
color6  #48B0BD
color14 #4CD1E0

# white
color7  #A0A8B7
color15 #E6E6E6
