# vim:ft=kitty

## name:     OneDark Warmer
## author:   Based on navarasu/onedark.nvim warmer palette
## blurb:    Kitty theme matching the onedark.nvim warmer variant.

# The basic colors
foreground              #A7AAB0
background              #232326
selection_foreground    #232326
selection_background    #A7AAB0

# Cursor colors
cursor                  #A7AAB0
cursor_text_color       #232326

# URL underline color when hovering with mouse
url_color               #57A5E5

# Tab bar colors
active_tab_foreground   #232326
active_tab_background   #A7AAB0
inactive_tab_foreground #A7AAB0
inactive_tab_background #2C2D31

# The 16 terminal colors

# black
color0 #2C2D31
color8 #535560

# red
color1 #DE5D68
color9 #E06C75

# green
color2  #8FB573
color10 #A5E075

# yellow
color3  #DBB671
color11 #E5C07B

# blue
color4  #57A5E5
color12 #4DC4FF

# purple
color5  #BB70D2
color13 #DE73FF

# cyan
color6  #51A8B3
color14 #4CD1E0

# white
color7  #A7AAB0
color15 #E6E6E6
